### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by aarongo** [go-sigma/sigma#274]
After the deployment is completed and the image is submitted, the image tag information cannot be displayed.

**Comment by aarongo** [comment]
![Snipaste_2024-01-08_19-45-04](https://github.com/go-sigma/sigma/assets/9677127/68b3f800-765d-42e8-96f6-ce3ba2603c20)
![Snipaste_2024-01-08_19-44-47](https://github.com/go-sigma/sigma/assets/9677127/aa4b0505-d57e-49a8-8df6-570c6d40c1f7)

**Comment by tosone** [comment]
Could you kindly provide your startup command, please? I will reproduce this issue.

**Comment by tosone** [comment]
You can use this startup command: `docker run --name sigma -p 3000:3000 --rm ghcr.io/go-sigma/sigma:nightly-alpine`
