### ISSUE TITLE
更改用户时出现 database is locked

### ISSUE THREAD

**Issue by Sokwva** [go-sigma/sigma#324]
从文档 https://github.com/go-sigma/demo-server/blob/main/sigma/config.yaml 复制配置内容直接粘贴到config.yaml后启动：

```bash
 ERR users/users_put.go:97 Delete role for user failed error="database is locked"
```

**Comment by tosone** [comment]
确实是一个问题，在数据库为 sqlite3 的时候会出现，我想一下怎么修复。

**Comment by tosone** [comment]
@Sokwva 你再试一下 `docker pull tosone/sigma:nightly-alpine` 这个最新的镜像试试？问题应该已经解决了。

**Comment by Sokwva** [comment]
> @Sokwva 你再试一下 `docker pull tosone/sigma:nightly-alpine` 这个最新的镜像试试？问题应该已经解决了。

这个问题已经恢复了，但是在push的时候明明已经login过了，但是还是现实authentification required，然后网页控制台进入repository，右上角弹出invalid request body，然后看日志是说
```bash
repositories/repositories_list.go:73 Bind and validate request body failed error="code=400, message=strconv.ParseInt: parsing \"null\": invalid syntax, internal=strconv.ParseInt: parsing \"null\": invalid syntax"
```

**Comment by tosone** [comment]
push 镜像提示登录的时候 sigma 里有什么日志么？

**Comment by tosone** [comment]
@Sokwva 你可以加我的联系方式，在主页的 readme 下方，你说的这个问题没有能复现出来。

**Comment by Sokwva** [comment]
> @Sokwva 你可以加我的联系方式，在主页的 readme 下方，你说的这个问题没有能复现出来。

好的

**Comment by tosone** [comment]
或许问题已经得到解决，如果还有问题欢迎重新打开。
