### ISSUE TITLE
Docker run failed with CentOS

### ISSUE THREAD

**Issue by funkpopo** [go-sigma/sigma#393]
在诸如CentOS、OpenEuler的系统上，尝试docker run时会返回下面的Fail提示
```bash
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
```
在Ubuntu上运行正常。看了下CI相关的文件，似乎是因为Ubuntu相关的配置或是特定的容器化平台或工具（skopeo）影响吗？

**Comment by tosone** [comment]
ci 中的 skopeo 只是拉取一些必要的镜像保存起来，当 sigma 用来构建镜像的时候会用到 skopeo 拉取到的东西。

**Comment by funkpopo** [comment]
抱歉回复晚了。
使用的镜像是nightly-alpine，但我回去使用1.3-alpine可正常启动
![image](https://github.com/user-attachments/assets/2c4a2472-1ab9-43f3-be64-14b6d98df5d6)

**Comment by tosone** [comment]
应该是这个 [issue](https://stackoverflow.com/questions/75710177/docker-pull-error-failed-to-register-layer-error-processing-tar-fileexit-sta) 导致的，或者你用 https://get.docker.com/ 这里的脚本安装一下最新版本的 docker ？

``` bash
sudo sh install-docker.sh --mirror Aliyun
```

**Comment by funkpopo** [comment]
看来确实是版本过于落后的问题，我记录了更新前使用的版本，Docker 18.09.0
由于其他原因暂时不能放弃CentOS，不过能解决就好。
感谢您的耐心帮助
